//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AMRMeter.SMSSerice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="mainserviceSoap", Namespace="http://tempuri.org/")]
    public partial class mainservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback knowyourofficerOperationCompleted;
        
        private System.Threading.SendOrPostCallback getsectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback illegal_sectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SENDTESTSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback mVaayoBulkSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendUniCodeSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendBulkSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendBulkSMSNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback CDAC_SMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback CDAC_SMS_NewOperationCompleted;
        
        private System.Threading.SendOrPostCallback SingleSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback RBSTCATEGORYIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback MvayooIMITestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public mainservice() {
            this.Url = global::AMRMeter.Properties.Settings.Default.AMRMeter_SMSSerice_mainservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event knowyourofficerCompletedEventHandler knowyourofficerCompleted;
        
        /// <remarks/>
        public event getsectionCompletedEventHandler getsectionCompleted;
        
        /// <remarks/>
        public event illegal_sectionCompletedEventHandler illegal_sectionCompleted;
        
        /// <remarks/>
        public event SENDTESTSMSCompletedEventHandler SENDTESTSMSCompleted;
        
        /// <remarks/>
        public event mVaayoBulkSMSCompletedEventHandler mVaayoBulkSMSCompleted;
        
        /// <remarks/>
        public event SendOTPCompletedEventHandler SendOTPCompleted;
        
        /// <remarks/>
        public event SendUniCodeSMSCompletedEventHandler SendUniCodeSMSCompleted;
        
        /// <remarks/>
        public event SendBulkSMSCompletedEventHandler SendBulkSMSCompleted;
        
        /// <remarks/>
        public event SendBulkSMSNewCompletedEventHandler SendBulkSMSNewCompleted;
        
        /// <remarks/>
        public event CDAC_SMSCompletedEventHandler CDAC_SMSCompleted;
        
        /// <remarks/>
        public event CDAC_SMS_NewCompletedEventHandler CDAC_SMS_NewCompleted;
        
        /// <remarks/>
        public event SingleSMSCompletedEventHandler SingleSMSCompleted;
        
        /// <remarks/>
        public event RBSTCATEGORYIDCompletedEventHandler RBSTCATEGORYIDCompleted;
        
        /// <remarks/>
        public event MvayooIMITestCompletedEventHandler MvayooIMITestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/knowyourofficer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet knowyourofficer(string can) {
            object[] results = this.Invoke("knowyourofficer", new object[] {
                        can});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void knowyourofficerAsync(string can) {
            this.knowyourofficerAsync(can, null);
        }
        
        /// <remarks/>
        public void knowyourofficerAsync(string can, object userState) {
            if ((this.knowyourofficerOperationCompleted == null)) {
                this.knowyourofficerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnknowyourofficerOperationCompleted);
            }
            this.InvokeAsync("knowyourofficer", new object[] {
                        can}, this.knowyourofficerOperationCompleted, userState);
        }
        
        private void OnknowyourofficerOperationCompleted(object arg) {
            if ((this.knowyourofficerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.knowyourofficerCompleted(this, new knowyourofficerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getsection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getsection(string Lat, string Long) {
            object[] results = this.Invoke("getsection", new object[] {
                        Lat,
                        Long});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getsectionAsync(string Lat, string Long) {
            this.getsectionAsync(Lat, Long, null);
        }
        
        /// <remarks/>
        public void getsectionAsync(string Lat, string Long, object userState) {
            if ((this.getsectionOperationCompleted == null)) {
                this.getsectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetsectionOperationCompleted);
            }
            this.InvokeAsync("getsection", new object[] {
                        Lat,
                        Long}, this.getsectionOperationCompleted, userState);
        }
        
        private void OngetsectionOperationCompleted(object arg) {
            if ((this.getsectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getsectionCompleted(this, new getsectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/illegal_section", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet illegal_section(string Lat, string Long) {
            object[] results = this.Invoke("illegal_section", new object[] {
                        Lat,
                        Long});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void illegal_sectionAsync(string Lat, string Long) {
            this.illegal_sectionAsync(Lat, Long, null);
        }
        
        /// <remarks/>
        public void illegal_sectionAsync(string Lat, string Long, object userState) {
            if ((this.illegal_sectionOperationCompleted == null)) {
                this.illegal_sectionOperationCompleted = new System.Threading.SendOrPostCallback(this.Onillegal_sectionOperationCompleted);
            }
            this.InvokeAsync("illegal_section", new object[] {
                        Lat,
                        Long}, this.illegal_sectionOperationCompleted, userState);
        }
        
        private void Onillegal_sectionOperationCompleted(object arg) {
            if ((this.illegal_sectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.illegal_sectionCompleted(this, new illegal_sectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SENDTESTSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SENDTESTSMS(string mobileno, string serialid, string templateid) {
            this.Invoke("SENDTESTSMS", new object[] {
                        mobileno,
                        serialid,
                        templateid});
        }
        
        /// <remarks/>
        public void SENDTESTSMSAsync(string mobileno, string serialid, string templateid) {
            this.SENDTESTSMSAsync(mobileno, serialid, templateid, null);
        }
        
        /// <remarks/>
        public void SENDTESTSMSAsync(string mobileno, string serialid, string templateid, object userState) {
            if ((this.SENDTESTSMSOperationCompleted == null)) {
                this.SENDTESTSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSENDTESTSMSOperationCompleted);
            }
            this.InvokeAsync("SENDTESTSMS", new object[] {
                        mobileno,
                        serialid,
                        templateid}, this.SENDTESTSMSOperationCompleted, userState);
        }
        
        private void OnSENDTESTSMSOperationCompleted(object arg) {
            if ((this.SENDTESTSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SENDTESTSMSCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mVaayoBulkSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string mVaayoBulkSMS(string mobileno, string serialid) {
            object[] results = this.Invoke("mVaayoBulkSMS", new object[] {
                        mobileno,
                        serialid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void mVaayoBulkSMSAsync(string mobileno, string serialid) {
            this.mVaayoBulkSMSAsync(mobileno, serialid, null);
        }
        
        /// <remarks/>
        public void mVaayoBulkSMSAsync(string mobileno, string serialid, object userState) {
            if ((this.mVaayoBulkSMSOperationCompleted == null)) {
                this.mVaayoBulkSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmVaayoBulkSMSOperationCompleted);
            }
            this.InvokeAsync("mVaayoBulkSMS", new object[] {
                        mobileno,
                        serialid}, this.mVaayoBulkSMSOperationCompleted, userState);
        }
        
        private void OnmVaayoBulkSMSOperationCompleted(object arg) {
            if ((this.mVaayoBulkSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mVaayoBulkSMSCompleted(this, new mVaayoBulkSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendOTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendOTP(string mobileno, string serialid, string templateid) {
            this.Invoke("SendOTP", new object[] {
                        mobileno,
                        serialid,
                        templateid});
        }
        
        /// <remarks/>
        public void SendOTPAsync(string mobileno, string serialid, string templateid) {
            this.SendOTPAsync(mobileno, serialid, templateid, null);
        }
        
        /// <remarks/>
        public void SendOTPAsync(string mobileno, string serialid, string templateid, object userState) {
            if ((this.SendOTPOperationCompleted == null)) {
                this.SendOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOTPOperationCompleted);
            }
            this.InvokeAsync("SendOTP", new object[] {
                        mobileno,
                        serialid,
                        templateid}, this.SendOTPOperationCompleted, userState);
        }
        
        private void OnSendOTPOperationCompleted(object arg) {
            if ((this.SendOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendOTPCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendUniCodeSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendUniCodeSMS(string mobileno, string serialid) {
            object[] results = this.Invoke("SendUniCodeSMS", new object[] {
                        mobileno,
                        serialid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendUniCodeSMSAsync(string mobileno, string serialid) {
            this.SendUniCodeSMSAsync(mobileno, serialid, null);
        }
        
        /// <remarks/>
        public void SendUniCodeSMSAsync(string mobileno, string serialid, object userState) {
            if ((this.SendUniCodeSMSOperationCompleted == null)) {
                this.SendUniCodeSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendUniCodeSMSOperationCompleted);
            }
            this.InvokeAsync("SendUniCodeSMS", new object[] {
                        mobileno,
                        serialid}, this.SendUniCodeSMSOperationCompleted, userState);
        }
        
        private void OnSendUniCodeSMSOperationCompleted(object arg) {
            if ((this.SendUniCodeSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendUniCodeSMSCompleted(this, new SendUniCodeSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendBulkSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendBulkSMS(string mobileno, string serialid) {
            object[] results = this.Invoke("SendBulkSMS", new object[] {
                        mobileno,
                        serialid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendBulkSMSAsync(string mobileno, string serialid) {
            this.SendBulkSMSAsync(mobileno, serialid, null);
        }
        
        /// <remarks/>
        public void SendBulkSMSAsync(string mobileno, string serialid, object userState) {
            if ((this.SendBulkSMSOperationCompleted == null)) {
                this.SendBulkSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBulkSMSOperationCompleted);
            }
            this.InvokeAsync("SendBulkSMS", new object[] {
                        mobileno,
                        serialid}, this.SendBulkSMSOperationCompleted, userState);
        }
        
        private void OnSendBulkSMSOperationCompleted(object arg) {
            if ((this.SendBulkSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBulkSMSCompleted(this, new SendBulkSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendBulkSMSNew", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendBulkSMSNew(string mobileno, string serialid) {
            object[] results = this.Invoke("SendBulkSMSNew", new object[] {
                        mobileno,
                        serialid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendBulkSMSNewAsync(string mobileno, string serialid) {
            this.SendBulkSMSNewAsync(mobileno, serialid, null);
        }
        
        /// <remarks/>
        public void SendBulkSMSNewAsync(string mobileno, string serialid, object userState) {
            if ((this.SendBulkSMSNewOperationCompleted == null)) {
                this.SendBulkSMSNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBulkSMSNewOperationCompleted);
            }
            this.InvokeAsync("SendBulkSMSNew", new object[] {
                        mobileno,
                        serialid}, this.SendBulkSMSNewOperationCompleted, userState);
        }
        
        private void OnSendBulkSMSNewOperationCompleted(object arg) {
            if ((this.SendBulkSMSNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBulkSMSNewCompleted(this, new SendBulkSMSNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CDAC_SMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CDAC_SMS(string mobileno, string serialid, string templateid) {
            this.Invoke("CDAC_SMS", new object[] {
                        mobileno,
                        serialid,
                        templateid});
        }
        
        /// <remarks/>
        public void CDAC_SMSAsync(string mobileno, string serialid, string templateid) {
            this.CDAC_SMSAsync(mobileno, serialid, templateid, null);
        }
        
        /// <remarks/>
        public void CDAC_SMSAsync(string mobileno, string serialid, string templateid, object userState) {
            if ((this.CDAC_SMSOperationCompleted == null)) {
                this.CDAC_SMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCDAC_SMSOperationCompleted);
            }
            this.InvokeAsync("CDAC_SMS", new object[] {
                        mobileno,
                        serialid,
                        templateid}, this.CDAC_SMSOperationCompleted, userState);
        }
        
        private void OnCDAC_SMSOperationCompleted(object arg) {
            if ((this.CDAC_SMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CDAC_SMSCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CDAC_SMS_New", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CDAC_SMS_New(string mobileno, string serialid, string templateid) {
            object[] results = this.Invoke("CDAC_SMS_New", new object[] {
                        mobileno,
                        serialid,
                        templateid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CDAC_SMS_NewAsync(string mobileno, string serialid, string templateid) {
            this.CDAC_SMS_NewAsync(mobileno, serialid, templateid, null);
        }
        
        /// <remarks/>
        public void CDAC_SMS_NewAsync(string mobileno, string serialid, string templateid, object userState) {
            if ((this.CDAC_SMS_NewOperationCompleted == null)) {
                this.CDAC_SMS_NewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCDAC_SMS_NewOperationCompleted);
            }
            this.InvokeAsync("CDAC_SMS_New", new object[] {
                        mobileno,
                        serialid,
                        templateid}, this.CDAC_SMS_NewOperationCompleted, userState);
        }
        
        private void OnCDAC_SMS_NewOperationCompleted(object arg) {
            if ((this.CDAC_SMS_NewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CDAC_SMS_NewCompleted(this, new CDAC_SMS_NewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SingleSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SingleSMS(string mobileno, string serialid, string templateid) {
            object[] results = this.Invoke("SingleSMS", new object[] {
                        mobileno,
                        serialid,
                        templateid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SingleSMSAsync(string mobileno, string serialid, string templateid) {
            this.SingleSMSAsync(mobileno, serialid, templateid, null);
        }
        
        /// <remarks/>
        public void SingleSMSAsync(string mobileno, string serialid, string templateid, object userState) {
            if ((this.SingleSMSOperationCompleted == null)) {
                this.SingleSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSingleSMSOperationCompleted);
            }
            this.InvokeAsync("SingleSMS", new object[] {
                        mobileno,
                        serialid,
                        templateid}, this.SingleSMSOperationCompleted, userState);
        }
        
        private void OnSingleSMSOperationCompleted(object arg) {
            if ((this.SingleSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SingleSMSCompleted(this, new SingleSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RBSTCATEGORYID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet RBSTCATEGORYID(string CAN) {
            object[] results = this.Invoke("RBSTCATEGORYID", new object[] {
                        CAN});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void RBSTCATEGORYIDAsync(string CAN) {
            this.RBSTCATEGORYIDAsync(CAN, null);
        }
        
        /// <remarks/>
        public void RBSTCATEGORYIDAsync(string CAN, object userState) {
            if ((this.RBSTCATEGORYIDOperationCompleted == null)) {
                this.RBSTCATEGORYIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRBSTCATEGORYIDOperationCompleted);
            }
            this.InvokeAsync("RBSTCATEGORYID", new object[] {
                        CAN}, this.RBSTCATEGORYIDOperationCompleted, userState);
        }
        
        private void OnRBSTCATEGORYIDOperationCompleted(object arg) {
            if ((this.RBSTCATEGORYIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RBSTCATEGORYIDCompleted(this, new RBSTCATEGORYIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MvayooIMITest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MvayooIMITest() {
            object[] results = this.Invoke("MvayooIMITest", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MvayooIMITestAsync() {
            this.MvayooIMITestAsync(null);
        }
        
        /// <remarks/>
        public void MvayooIMITestAsync(object userState) {
            if ((this.MvayooIMITestOperationCompleted == null)) {
                this.MvayooIMITestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMvayooIMITestOperationCompleted);
            }
            this.InvokeAsync("MvayooIMITest", new object[0], this.MvayooIMITestOperationCompleted, userState);
        }
        
        private void OnMvayooIMITestOperationCompleted(object arg) {
            if ((this.MvayooIMITestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MvayooIMITestCompleted(this, new MvayooIMITestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void knowyourofficerCompletedEventHandler(object sender, knowyourofficerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class knowyourofficerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal knowyourofficerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void getsectionCompletedEventHandler(object sender, getsectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getsectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getsectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void illegal_sectionCompletedEventHandler(object sender, illegal_sectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class illegal_sectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal illegal_sectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SENDTESTSMSCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void mVaayoBulkSMSCompletedEventHandler(object sender, mVaayoBulkSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mVaayoBulkSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mVaayoBulkSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendOTPCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendUniCodeSMSCompletedEventHandler(object sender, SendUniCodeSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendUniCodeSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendUniCodeSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendBulkSMSCompletedEventHandler(object sender, SendBulkSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBulkSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBulkSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SendBulkSMSNewCompletedEventHandler(object sender, SendBulkSMSNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBulkSMSNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBulkSMSNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CDAC_SMSCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CDAC_SMS_NewCompletedEventHandler(object sender, CDAC_SMS_NewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CDAC_SMS_NewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CDAC_SMS_NewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SingleSMSCompletedEventHandler(object sender, SingleSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SingleSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SingleSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void RBSTCATEGORYIDCompletedEventHandler(object sender, RBSTCATEGORYIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RBSTCATEGORYIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RBSTCATEGORYIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void MvayooIMITestCompletedEventHandler(object sender, MvayooIMITestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MvayooIMITestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MvayooIMITestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591